In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cv2 as cv
from patchify import patchify
import PIL
from PIL import Image
PIL.Image.MAX_IMAGE_PIXELS = 933120000
import os
import shutil
import random
%matplotlib inline
import torchvision
import torch
from torch.utils.data import Dataset,DataLoader
from torchvision import datasets, transforms
from torch import nn
from torch import optim
import torch.nn.functional as F
import statistics

In [2]:
img = cv.imread("E:\PG_HP_FINAL\CAE Map Reconstruction\90721368.27.tif")
print(img.shape)

(13366, 18460, 3)


In [2]:
map_name_list = os.listdir('../OS_map')
print(map_name_list)
for map_name in map_name_list:
    map_name_path = '../OS_map/'+map_name
    print(map_name_path)

['OS_82877409.tif', 'OS_82877412.tif', 'OS_82877415.tif', 'OS_82877418.tif']
../OS_map/OS_82877409.tif
../OS_map/OS_82877412.tif
../OS_map/OS_82877415.tif
../OS_map/OS_82877418.tif


In [6]:
img412 = cv.imread('../OS_map/OS_82877412.tif')
# img412 = cv2.cvtColor(img412, cv2.COLOR_BGR2RGB)
print("img412 shape is",img412.shape)

img415 = cv.imread('../OS_map/OS_82877415.tif')
# img415 = cv2.cvtColor(img415, cv2.COLOR_BGR2RGB)
print("img415 shape is",img415.shape)

img418 = cv.imread('../OS_map/OS_82877418.tif')
# img418 = cv2.cvtColor(img418, cv2.COLOR_BGR2RGB)
print("img418 shape is",img418.shape)


img412 = img412[:10166,:15249]
img415 = img415[:10166,:15249]
img418 = img418[:10166,:15249]


print("img412 shape is",img412.shape)
print("img415 shape is",img415.shape)
print("img418 shape is",img418.shape)

# img415_CLAHE = cv.imread("E:\HP\Week9\OS_415_CLAHE.tif")
# print("img415_CLAHE shape is",img415_CLAHE.shape)
# img415_CLAHE = img415_CLAHE[:10166,:15249]
# print("img415_CLAHE shape is",img415_CLAHE.shape)

# img418_CLAHE = cv.imread("E:\HP\Week9\OS_418_CLAHE.tif")
# print("img418_CLAHE shape is",img418_CLAHE.shape)
# img418_CLAHE = img418_CLAHE[:10166,:15249]
# print("img418_CLAHE shape is",img418_CLAHE.shape)

# img415_HE = cv.imread("E:\HP\Week9\OS_415_HistEqu.tif")
# print("img415_HE shape is",img415_HE.shape)
# img415_HE = img415_CLAHE[:10166,:15249]
# print("img415_HE shape is",img415_HE.shape)

# img418_HE = cv.imread("E:\HP\Week9\OS_418_HistEqu.tif")
# print("img418_HE shape is",img418_HE.shape)
# img418_HE = img418_HE[:10166,:15249]
# print("img418_HE shape is",img418_HE.shape)

# img_412 = np.array(img412)
# img_412 = img_412[:10166,:15249]
# print("img_412 shape is",img_412.shape)

# img_415 = np.array(img415)
# img_415 = img_415[:10166,:15249]
# print("img_415 shape is",img_415.shape)

# img_418 = np.array(img418)
# img_418 = img_418[:10166,:15249]
# print("img_418 shape is",img_418.shape)

img412 shape is (10166, 15249, 3)
img415 shape is (10169, 15254, 3)
img418 shape is (10178, 15266, 3)
img412 shape is (10166, 15249, 3)
img415 shape is (10166, 15249, 3)
img418 shape is (10166, 15249, 3)


In [10]:
imgHist = cv.imread("E:\HP\Paper_writing\OS_82877415_HistEqu.tif")

print(imgHist.shape)

(10169, 15254, 3)


In [11]:
patch_width = 64
tif_map_patches = patchify(image = imgHist , patch_size = (patch_width, patch_width,3),step = patch_width)
row = tif_map_patches.shape[0]
col = tif_map_patches.shape[1]
tif_map_patches = tif_map_patches.reshape(row, col, patch_width, patch_width, 3)
for i in range(row):
    for j in range(col):
        patch = tif_map_patches[i][j]
        path = '415_HIST/patch_{r}_{c}.png'.format(r=i,c=j)
        cv.imwrite(path,patch)

In [3]:
img = cv.imread("E:\PG_HP_FINAL\CAE Map Reconstruction\90721368.27.tif")
print(img.shape)

(13366, 18460, 3)


In [7]:
patch_width = 256
tif_map_patches = patchify(image = img , patch_size = (patch_width, patch_width,3),step = patch_width)
row = tif_map_patches.shape[0]
col = tif_map_patches.shape[1]
tif_map_patches = tif_map_patches.reshape(row, col, patch_width, patch_width, 3)
for i in range(row):
    for j in range(col):
        patch = tif_map_patches[i][j]
        
        path = 'Batho_90721368(256)/patch_{r}_{c}.png'.format(r=i,c=j)
        cv.imwrite(path,patch)

In [15]:
output_patches = np.empty(img_418.shape).astype(np.uint8)
print(output_patches.shape)
print(output_patches)

(10166, 15249, 3)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [23]:
row = img_418.shape[0]
col = img_418.shape[1]
for i in range(row):
    for j in range(col):
        img412_x = img_412[i][j][0]
        img412_y = img_412[i][j][1]
        img412_z = img_412[i][j][2]
        
        img415_x = img_415[i][j][0]
        img415_y = img_415[i][j][1]
        img415_z = img_415[i][j][2]
        
        img418_x = img_418[i][j][0]
        img418_y = img_418[i][j][1]
        img418_z = img_418[i][j][2]
        
        output_patches[i][j][0] = statistics.median([img412_x,img415_x,img418_x])                                            
        output_patches[i][j][1] = statistics.median([img412_y,img415_y,img418_y])
        output_patches[i][j][2] = statistics.median([img412_z,img415_z,img418_z])                                           

In [24]:
# print(output_image.shape)
cv.imwrite("MedianValue2_Image_412415418.tif",output_patches)

True

In [7]:
print("img_418 shape is",img_418.shape)

img_418 shape is (10166, 15249, 3)


In [14]:
patch_width = 5000
tif_map_patches = patchify(image = img_415, patch_size = (patch_width, patch_width,3),step = patch_width)
row = tif_map_patches.shape[0]
col = tif_map_patches.shape[1]
tif_map_patches = tif_map_patches.reshape(row, col, patch_width, patch_width, 3)
for i in range(row):
    for j in range(col):
        patch = tif_map_patches[i][j]
        path = 'OS_415(5000)/patch_{r}_{c}.tif'.format(r=i,c=j)
        cv.imwrite(path,patch)

In [3]:
patch_width = 64
tif_map_patches = patchify(image = img_median, patch_size = (patch_width, patch_width,3),step = patch_width)
row = tif_map_patches.shape[0]
col = tif_map_patches.shape[1]
tif_map_patches = tif_map_patches.reshape(row, col, patch_width, patch_width, 3)
for i in range(row):
    for j in range(col):
        patch = tif_map_patches[i][j]
        path = 'OS_Median[412_415_418]/patch_{r}_{c}.tif'.format(r=i,c=j)
        cv.imwrite(path,patch)

In [4]:
patch_width = 128
tif_map_patches = patchify(image = img_415, patch_size = (patch_width, patch_width,3),step = patch_width)
row = tif_map_patches.shape[0]
col = tif_map_patches.shape[1]
tif_map_patches = tif_map_patches.reshape(row, col, patch_width, patch_width, 3)
for i in range(row):
    for j in range(col):
        patch = tif_map_patches[i][j]
        path = 'OS_415(128)/patch_{r}_{c}.tif'.format(r=i,c=j)
        cv.imwrite(path,patch)

In [5]:
patch_width = 256
tif_map_patches = patchify(image = img_415, patch_size = (patch_width, patch_width,3),step = patch_width)
row = tif_map_patches.shape[0]
col = tif_map_patches.shape[1]
tif_map_patches = tif_map_patches.reshape(row, col, patch_width, patch_width, 3)
for i in range(row):
    for j in range(col):
        patch = tif_map_patches[i][j]
        path = 'OS_415(256)/patch_{r}_{c}.tif'.format(r=i,c=j)
        cv.imwrite(path,patch)

In [5]:
patch_width = 64
tif_map_patches = patchify(image = img_415 , patch_size = (patch_width, patch_width,3),step = patch_width)
row = tif_map_patches.shape[0]
col = tif_map_patches.shape[1]
tif_map_patches = tif_map_patches.reshape(row, col, patch_width, patch_width, 3)
for i in range(row):
    for j in range(col):
        patch = tif_map_patches[i][j]
        path = 'OS_415(64)/patch_{r}_{c}.tif'.format(r=i,c=j)
        cv.imwrite(path,patch)

In [8]:
patch_width = 64
tif_map_patches = patchify(image = img_418 , patch_size = (patch_width, patch_width,3),step = patch_width)
row = tif_map_patches.shape[0]
col = tif_map_patches.shape[1]
tif_map_patches = tif_map_patches.reshape(row, col, patch_width, patch_width, 3)
for i in range(row):
    for j in range(col):
        patch = tif_map_patches[i][j]
        path = 'OS_418(64)/patch_{r}_{c}.tif'.format(r=i,c=j)
        cv.imwrite(path,patch)